### PR TITLE
Warren's Update

### PR DESCRIPTION
**Pull request by warrenkc**

### CODE REVIEW

**Review by warrenkc — COMMENTED** [review]
Moved translate_client to be global variable.

**Comment by warrenkc** [comment]
I found some interesting results from testing stereo mix input versus microphone input. [See video](https://drive.google.com/open?id=1hbG3YRTBYnLRY9TEAStkT25M-OvZVnMB).

**Comment by xellosiris** [comment]
Be honest, when I wrote the code, I was confused about single_utterence in speech streaming config.(https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#google.cloud.speech.v1.StreamingRecognitionConfig)
Even though  I did not put single_utterence into config ,the code still working when I use mic.I thought maybe this is a reason why respond can't be stop when you using mix audio input.

Fixed:
 Put break when result.is_final



Put single_utterance into config and mic obj in while loop:

**Comment by xellosiris** [comment]
Sorry break should put after if statement(after send to zoom)

**Review by xellosiris — APPROVED** [review]

**Pull request closed without merging**
